linters-settings:
  gocritic:
    enabled-tags:
    - diagnostic
    - experimental
    - opinionated
    - performance
    - style
    disabled-checks:
    # This test is disabled because it's frequently used with loop control flow.
    # Using `switch` would change the target of a `break` and unless a developer
    # is responsible they'll end up breaking out of the wrong control structure.
    - ifElseChain
    # This test is disabled because it's an edge case that we have not
    # encountered anyone accidentally using (i.e., if you put in a pointer to an
    # interface, you actually do need it for some reason).
    - ptrToRefParam
    # This test is also disabled because it's frequently used with loop control
    # flow.
    - typeAssertChain
    settings:
      hugeParam:
        sizeThreshold: 512
  gocyclo:
    min-complexity: 20
  nolintlint:
    allow-leading-space: true
    allow-unused: false
    require-explanation: false
    require-specific: true

linters:
  disable-all: true
  enable:
  - bodyclose
  - deadcode
  - errcheck
  - exportloopref
  - gocritic
  - gocyclo
  - goimports
  - gosec
  - gosimple
  - govet
  - ineffassign
  - noctx
  - nolintlint
  - staticcheck
  - structcheck
  - typecheck
  - unused
  - varcheck

issues:
  exclude-rules:
  - path: _test\.go$
    linters:
    - bodyclose
    - noctx
