apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: relay-install-operator
rules:
- apiGroups:
  - ""
  - apps
  - rbac.authorization.k8s.io
  - admissionregistration.k8s.io
  - networking.k8s.io
  - rbac.authorization.k8s.io
  resources:
  - clusterroles
  - clusterrolebindings
  - configmaps
  - deployments
  - limitranges
  - mutatingwebhookconfigurations
  - namespaces
  - secrets
  - serviceaccounts
  - services
  - roles
  - rolebindings
  - statefulsets
  verbs:
  - '*'
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - install.relay.sh
  resources:
  - relaycores
  - relaycores/status
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - relay.sh
  resources:
  - runs
  - runs/status
  - tenants
  - tenants/status
  - webhooktriggers
  - webhooktriggers/status
  - workflows
  - workflows/status
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - serving.knative.dev
  resources:
  - revisions
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tekton.dev
  resources:
  - conditions
  - pipelineruns
  - pipelines
  - taskruns
  - tasks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
