apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: controller
subjects:
- kind: ServiceAccount
  name: controller
  namespace: default
roleRef:
  kind: ClusterRole
  name: controller
  apiGroup: rbac.authorization.k8s.io
