apiVersion: apps/v1
kind: Deployment
metadata:
  name: relay-installer
  namespace: relay-installer
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: controller
      app.kubernetes.io/name: relay-installer
  template:
    metadata:
      labels:
        app.kubernetes.io/component: controller
        app.kubernetes.io/name: relay-installer
    spec:
      containers:
      - image: us-docker.pkg.dev/puppet-relay-contrib-oss/relay-core/relay-installer
        imagePullPolicy: IfNotPresent
        name: controller
        resources:
          limits:
            cpu: 50m
            memory: 64Mi
          requests:
            cpu: 25m
            memory: 32Mi
      serviceAccountName: relay-installer
