apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- install.relay.sh_relaycores.yaml
- namespace.yaml
- serviceaccount.yaml
- clusterrole.yaml
- clusterrolebinding.yaml
- deployment.yaml
