apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: relay-core-v1-operator
  namespace: relay-system
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
