apiVersion: v1
kind: ServiceAccount
metadata:
  name: relay-core-v1-operator
  namespace: relay-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: relay-install-operator
  namespace: relay-system
